### ISSUE TITLE
No attribute graph def?

### ISSUE THREAD

**Issue by mkemka** [openai/CLIP-featurevis#3]
In the model file there is a self.graph_def referenced on line 38 but I can't seem to see where it is defined.

**Comment by ModMorph** [comment]
Getting same error. I wonder if the versions of libraries are off somehow for anyone installing this now for the first time since only the tensorflow-gpu==1.13.2 has a version? Seems like something subtle. I tried rolling back lucid to older version with same error message, so not sure if that excludes it. Maybe pip list showing versions from someone who has it working could help isolate problem? 

Trace:trying to run example_usage.py 

  self.T   = render.import_model(self, self.inp, self.inp)
  File "/usr/local/lib/python3.6/dist-packages/lucid/optvis/render.py", line 254, in import_model
    model.import_graph(t_image, scope="import", forget_xy_shape=True)
  File "/usr/local/lib/python3.6/dist-packages/lucid/modelzoo/vision_base.py", line 66, in import_graph
    if self.graph_def is None:
AttributeError: 'CLIPImage' object has no attribute 'graph_def'

If somehow related/same issue I get a different error on example_facets mkemka:
Traceback (most recent call last):
  File "example_facets.py", line 14, in <module>
    @wrap_objective()
TypeError: wrap_objective() missing 1 required positional argument: 'func'

**Comment by mkemka** [comment]
Ah you have good timing as I am looking at this again now.
Perhaps try to update to tensorflow-gpu==1.14 . 

If you look at the CLIPImage class there is no "self.graph_def". Happy to be corrected but it looks like the code is incomplete. I don't know how it can reference an attribute of itself that doesn't exist.

**Comment by ProGamerGov** [comment]
@mkemka The CLIPImage class inherits the `self.graph_def` variable from Lucid's model class: https://github.com/tensorflow/lucid/blob/master/lucid/modelzoo/vision_base.py#L91 . I'm not sure why it's not working?

I'm also running into the

```
@wrap_objective()
TypeError: wrap_objective() missing 1 required positional argument: 'func'
```

**Comment by mkemka** [comment]
Ah you are right - for some reason I misread the inheritance. My mistake. I can have a look at this issue.

**Comment by ProGamerGov** [comment]
You should also be able to get the right TensorFlow version on Colab by doing this:

```
%tensorflow_version 1.x
import tensorflow as tf
```

**Comment by ProGamerGov** [comment]
@mkemka Try downloading the model and changing the model_path attribute to match the downloaded location. That fixes the issue for me!

Have you solved the wrapper issue yet?

**Comment by mkemka** [comment]
I am testing in collab now and still getting the graphdef issue.

**Comment by BoneAmputee** [comment]
This works. I'm not sure if it's the best way to do things, but it works.
https://colab.research.google.com/drive/1WWo2L7ZMdslbZyOg-pqzFeRK6PQWoDjw

**Comment by BoneAmputee** [comment]
https://colab.research.google.com/drive/1WWo2L7ZMdslbZyOg-pqzFeRK6PQWoDjw

**Comment by mkemka** [comment]
Ah I see you don't have a specific tf library. Maybe that is part of the trick?

**Comment by BoneAmputee** [comment]
1.15.2 seems to be working for me

I resolved the graph_def thing by adding these to model.py
```python
with tf.gfile.GFile('image32.pb', "rb") as f:
  self.graph_def = tf.GraphDef()
  self.graph_def.ParseFromString(f.read())
```

and fixed the `@wrap_object()` issue by removing the `()`

**Comment by mkemka** [comment]
Thank you so much for this. Unless there are other fixes with the library I can close this issue.
